# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: my_theme_nord
  theme_night: my_theme_nord
  font: my_font_set_nord
  font_size: L # Use L for optimal accessibility metric on Lighthouse

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: Personal website of Dr. Kenneth Tyler Wilcox
    twitter: 'KTylerWilcox'
  analytics:
    google_analytics: 'UA-92616491-2'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer
footer:
  copyright:
    notice: '© {year} Kenneth Tyler Wilcox. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - cpp
      - python
      - stan
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/ktw5691/wilcoxkt-academic-site'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true

# publications:
#   date_format: January 2006
#   citation_style: apa
# projects:
#   post_view: 2
#   publication_view: 4
#   talk_view: 4
# breadcrumb:
#   page_types:
#     book: true
# icon:
#   pack:
#     ai: true
# security.csp:
#   policy: ''
#   report_only: false
