# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: my_theme_nord
day_night: true
font: my_font_set_nord
# Speed optimized, Google free alternative
# font: native
font_size: L # Use L for optimal accessibility metric on Lighthouse

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: Personal website of Kenneth Tyler Wilcox
twitter: ''

# Contact (edit or remove options as required)

email: kwilcox3@nd.edu
phone: ''
address:
  street: 390 Corbett Family Hall, Department of Psychology, University of Notre Dame
  city: Notre Dame
  region: IN
  postcode: '46556'
  country: United States
  country_code: US
coordinates:
  latitude: ''
  longitude: ''
directions:
office_hours:
appointment_url: 'https://kwilcox3.youcanbook.me'
contact_links:
  - icon: google-scholar
    icon_pack: ai
    name: Google Scholar
    link: https://scholar.google.com/citations?user=GllwRa8AAAAJ&hl
  - icon: researchgate
    icon_pack: fab
    name: ResearchGate
    link: https://www.researchgate.net/profile/Kenneth_Wilcox
  - icon: github
    icon_pack: fab
    name: Github
    link: https://github.com/ktw5691
  - icon: orcid
    icon_pack: ai
    name: ORCiD
    link: https://orcid.org/0000-0003-3969-0427

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
highlight_languages:
  - r
  - cpp
  - python
  - stan
# highlight_style: github
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: 'https://github.com/ktw5691/academic-kickstart'
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: true
  post: true
  project: true
  publication: true
  event: true
reading_time: false
section_pager: true
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 200
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 4
  talk_view: 4
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  api_key: ''
  engine: ''
  zoom: 15
marketing:
  google_analytics: UA-92616491-2
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
  netlify_cms: true
icon:
  pack:
    ai: true
security.csp:
  policy: ''
  report_only: false
